"""Generates docs/localization_hardcoded_audit.md.

Classifies every literal that tool/extract_ui_strings.py reports in a UI
position into exactly one of five categories:

  1. dynamic / user / backend content that must NOT be translated
  2. protected bottom-navigation English
  3. internal technical value, or a fixed name no language changes
  4. a missed translation  <- the outstanding work; the audit only passes at 0
  5. approved English-only legal document content awaiting professional
     translation (Privacy Policy and Terms bodies only)

Every classification carries a reason. Deliberately, none of the rules is a
blanket "skip this file": the two file-scoped rules that exist (generated
FlutterFire config, the marked legal bodies) both require corroborating
evidence inside the file itself, and anything else that is genuinely not
translatable is annotated one line at a time with

    // l10n-ignore: <why>

so that every exclusion is visible in the source and in this report.

Run:  python tool/audit_report.py
"""

import io
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_ui_strings import scan  # noqa: E402

# Screens that exist in the tree but nothing routes to or imports.
DEAD_FILES = {
    "lib/features/auth/presentation/login_screen.dart",
    "lib/features/auth/presentation/register_screen.dart",
    # Client-local copies that nothing imports. Both profile pages use the
    # lib/core/presentation/pages/ versions instead.
    "lib/features/client/presentation/pages/general_info_page.dart",
    "lib/features/client/presentation/pages/privacy_policy_page.dart",
    "lib/features/client/presentation/pages/terms_conditions_page.dart",
    # Superseded by the private _HomeServiceItem list inside client_home_page.
    "lib/features/client/presentation/widgets/service_data.dart",
}

NUMERIC_MASK = re.compile(r"^[0-9X\s:/.,%+-]+$")
# Identifiers used as switch cases, map keys or option values — internal.
# snake_case tokens: switch cases, map keys, API/sync reasons and
# SharedPreferences key builders. Segments may carry digits (`backup_5m`) or be
# an interpolated id (`worker_avatar_path_$userId`) — display copy never looks
# like this, so the shape alone is proof it is internal.
INTERNAL_TOKEN = re.compile(
    r"^[a-z][a-z0-9]*(_(?:[a-z0-9]+|\$\{?\w+\}?))+$"
    r"|^[a-z]+:[a-z]+$|^[a-z]+,[a-z_]+$"
)
FILE_FRAGMENT = re.compile(r"^\.?[a-z]*\.(jpg|jpeg|png|webp|mp4|mov)$|^\)\.first\}$|^\.\$\{")
# A bare `$name`, or exactly one `${...}` group and nothing else. The braces
# have to balance: an earlier version allowed any characters between `${` and
# the final `}`, which quietly swallowed real copy like `'$all total'`.
PURE_INTERPOLATION = re.compile(
    r"^\$\w+$"
    r"|^\$\{(?:[^{}]|\{[^{}]*\})*\}$"
)
# A string built only from interpolations plus separators carries no words of
# its own, so there is nothing to translate.
INTERPOLATION_ONLY = re.compile(r"^(\s*\$\{[^}]*\}|\s*\$\w+|[\s,.:;/·—-]|\.\.\.)+$")
TIME_FORMAT = re.compile(r"^\$\w+:\$\{.*padLeft.*$")
# A `${` the captured value never closes: the literal was cut off inside an
# interpolation because the expression contains its own quote.
TRUNCATED_INTERPOLATION = re.compile(r"\$\{[^}]*$")
# `'⚠️'` in source: an emoji written as escapes.
ESCAPED_SYMBOL = re.compile(r"(\\u[0-9a-fA-F]{4})+")
BRANDS = {"HandyGo", "Handygo", "EasyRepair"}

# An Android/iOS resource reference: `@mipmap/ic_launcher`, `@drawable/x`.
PLATFORM_RESOURCE = re.compile(r"^@(mipmap|drawable|color|string|style|anim)/")

# BCP-47 subtags. `ur_Latn` is what SharedPreferences stores and `Latn` is the
# script code handed to Locale.fromSubtags — changing either would silently
# reset every user's language choice.
LOCALE_SUBTAG = re.compile(r"^[a-z]{2}(_[A-Z][a-z]{3})?$|^[A-Z][a-z]{3}$")

# How each language names itself in the language selector. Deliberately not
# translated: someone who cannot read the current language still has to be
# able to find their own in the list.
LANGUAGE_ENDONYMS = {"English", "اردو", "Roman Urdu"}

# The one generated file whose "strings" are Firebase project configuration:
# API keys, app ids, sender ids, bucket and bundle identifiers. Recognised by
# path AND by the FlutterFire CLI banner, so neither a hand-written file with
# this name nor an unrelated file carrying the banner is swept up.
FIREBASE_CONFIG_PATH = "lib/firebase_options.dart"
FIREBASE_CONFIG_BANNER = "// File generated by FlutterFire CLI."

# Approved English-only legal documents (Category 5). A literal counts only
# when it sits between the L10N-LEGAL-BODY markers *and* lives in one of these
# two files, so the marker cannot be used to hide ordinary UI elsewhere.
LEGAL_BODY_FILES = {
    "lib/core/presentation/pages/privacy_policy_page.dart",
    "lib/core/presentation/pages/terms_conditions_page.dart",
}
LEGAL_START = "L10N-LEGAL-BODY:START"
LEGAL_END = "L10N-LEGAL-BODY:END"

# A one-line, reasoned opt-out. The reason is mandatory and is printed in the
# report, so an exclusion cannot be made silently.
L10N_IGNORE = re.compile(r"//\s*l10n-ignore:\s*(?P<reason>.+?)\s*$")


def _line_of(src, line_no):
    lines = src.splitlines()
    return lines[line_no - 1] if 0 < line_no <= len(lines) else ""


def _enclosing(src, line_no, span=16):
    """A few lines above the hit — enough to see debugPrint / queryParameters."""
    lines = src.splitlines()
    lo = max(0, line_no - span)
    return "\n".join(lines[lo:line_no + 1])


def _in_debug_print(src, line_no, lookback=6):
    """True only when the literal is genuinely an argument of a debugPrint.

    Merely having a debugPrint somewhere in the surrounding block is not
    enough: a button label two lines below a debug line is still a button
    label. So walk back to the nearest `debugPrint(` and confirm its argument
    list is still open where the literal sits.
    """
    lines = src.splitlines()
    if not 0 < line_no <= len(lines):
        return False
    for start in range(line_no - 1, max(-1, line_no - 1 - lookback), -1):
        col = lines[start].find("debugPrint(")
        if col < 0:
            continue
        if start == line_no - 1:
            return True  # literal sits on the debugPrint line itself
        # Count only the lines strictly before the literal's: the literal's own
        # line usually carries the call's closing paren, which would otherwise
        # make an still-open call look balanced.
        segment = lines[start][col + len("debugPrint"):]
        for mid in range(start + 1, line_no - 1):
            segment += lines[mid]
        # The call is still open at the literal's line iff more '(' than ')'.
        return segment.count("(") > segment.count(")")
    return False


# Literals that are identifiers or belong to another feature's scope. Each was
# verified in context; the reason is what the audit prints.
CONTEXT_RULES = [
    ("post_job_page compares this against its slot/window ids",
     lambda l, b: "NOT display text" in b),
    ("Booking reference format, not translatable copy",
     lambda l, b: "shortId" in b),
    ("Data-layer default for a backend free-text field",
     lambda l, b: "json[" in l),
    ("Sync reason sent to the /workers/location API, never displayed",
     lambda l, b: "_pushToServer(" in b or "syncReason" in b),
    ("Numeric score format, identical in every language",
     lambda l, b: "toStringAsFixed" in l and "/5" in l),
]


def legal_body_range(path, src):
    """(start, end) line numbers of the approved legal body, or None.

    Both the path and the markers have to agree; a marker on its own proves
    nothing, and neither does the filename.
    """
    if path not in LEGAL_BODY_FILES:
        return None
    start = end = None
    for index, line in enumerate(src.splitlines(), start=1):
        if LEGAL_START in line and start is None:
            start = index
        elif LEGAL_END in line:
            end = index
    if start is None or end is None or end <= start:
        return None
    return (start, end)


def ignore_reason(src, line_no):
    """The `// l10n-ignore: <why>` covering this literal, if there is one.

    Accepted on the literal's own line or on either of the two lines above it,
    which is enough for a one-line function or an annotated `return`.
    """
    lines = src.splitlines()
    for probe in range(line_no, max(0, line_no - 3), -1):
        if not 0 < probe <= len(lines):
            continue
        match = L10N_IGNORE.search(lines[probe - 1])
        if match:
            return match.group("reason")
    return None


def _in_request_map(src, line_no, lookback=8):
    """True when the literal sits inside an open `queryParameters: {`/`headers: {`.

    Merely mentioning `queryParameters` somewhere above is not enough — a page
    that reads `state.uri.queryParameters['title']` and then supplies a
    *display* fallback a few lines later was being written off as an API value
    by that looser test.
    """
    lines = src.splitlines()
    if not 0 < line_no <= len(lines):
        return False
    opener = re.compile(r"\b(queryParameters|headers)\s*:\s*\{")
    for start in range(line_no - 1, max(-1, line_no - 1 - lookback), -1):
        match = opener.search(lines[start])
        if not match:
            continue
        if start == line_no - 1:
            return True
        segment = lines[start][match.end() - 1:]
        for mid in range(start + 1, line_no - 1):
            segment += lines[mid]
        return segment.count("{") > segment.count("}")
    return False


def classify(
    path,
    value,
    line_ctx="",
    block_ctx="",
    in_debug_print=False,
    in_request_map=False,
    is_firebase_config=False,
    in_legal_body=False,
    ignored_because=None,
):
    if in_legal_body:
        return 5, ("Approved English-only legal document text - awaiting a "
                   "professional Urdu / Roman Urdu translation, see "
                   "docs/legal_translation_exclusions.md")
    if is_firebase_config:
        return 3, ("Generated Firebase configuration value (FlutterFire CLI) "
                   "- an API key, app/sender/project id, bucket or bundle "
                   "identifier, never displayed")
    if ignored_because:
        return 3, "%s (// l10n-ignore)" % ignored_because
    if path in DEAD_FILES:
        return 3, "Unreachable legacy scaffold - nothing routes to or imports it"
    if "bottom_nav_bar" in path:
        return 2, "Protected bottom-navigation label, intentionally English"
    if value.strip() in BRANDS:
        return 3, "Brand name - never translated"
    if value.strip() in LANGUAGE_ENDONYMS and "displayLabel" in block_ctx:
        return 3, ("Language endonym in the selector - each language names "
                   "itself so a user who cannot read the current language can "
                   "still find their own")
    if LOCALE_SUBTAG.match(value) and (
        "Locale" in block_ctx or "storageValue" in block_ctx
    ):
        return 3, "BCP-47 locale subtag / persisted settings value, not display copy"
    if PLATFORM_RESOURCE.match(value):
        return 3, "Android/iOS resource reference, not display copy"
    if NUMERIC_MASK.match(value):
        return 3, "Numeric/format mask - identical in every language, stays Latin"
    if INTERNAL_TOKEN.match(value):
        return 3, "Internal identifier (switch case / map key / API parameter)"
    if FILE_FRAGMENT.match(value):
        return 3, "Filename or URL fragment, not display copy"
    # Context beats shape: the same interpolation is a log line in one place
    # and an API parameter in another, and neither is display copy.
    if in_debug_print or "print(" in line_ctx:
        return 3, "Developer log, never shown to a user"
    if in_request_map:
        return 3, "HTTP request parameter sent to an external API"
    if TIME_FORMAT.match(value):
        return 3, "Numeric time format (mm:ss), identical in every language"
    # A string that already resolves through context.l10n is localized; the
    # scanner only sees the surrounding template.
    if "context.l10n" in value:
        return 1, "Already localized — the literal is only a separator"
    if PURE_INTERPOLATION.match(value) or INTERPOLATION_ONLY.match(value):
        return 1, "Pure interpolation of dynamic/user/backend data"
    if TRUNCATED_INTERPOLATION.search(value):
        # The scanner's literal regex stops at the first quote, so a nested
        # quote inside `${cond ? a : ''}` cuts the value mid-interpolation.
        # What it captured is an expression, not copy.
        return 1, ("Scanner cut this mid-`${...}` interpolation - dynamic "
                   "content, nothing to translate")
    for reason, matches in CONTEXT_RULES:
        if matches(line_ctx, block_ctx):
            return 3, reason
    if not any(ch.isalnum() for ch in value):
        return 3, "Symbol or emoji, nothing to translate"
    # A bare escape sequence is an emoji or symbol in source form.
    if ESCAPED_SYMBOL.fullmatch(value):
        return 3, "Escaped emoji/symbol, nothing to translate"
    return 4, "App-owned visible text still hard-coded - NOT YET MIGRATED"


def main():
    rows = []
    for root, _dirs, files in os.walk("lib"):
        if os.path.normpath(root).endswith(os.path.join("lib", "l10n")):
            continue
        for name in sorted(files):
            if not name.endswith(".dart"):
                continue
            path = os.path.join(root, name).replace(os.sep, "/")
            src = io.open(path, encoding="utf-8").read()
            is_firebase = (
                path == FIREBASE_CONFIG_PATH and FIREBASE_CONFIG_BANNER in src
            )
            legal = legal_body_range(path, src)
            for line, value in scan(path):
                category, reason = classify(
                    path,
                    value,
                    _line_of(src, line),
                    _enclosing(src, line),
                    _in_debug_print(src, line),
                    in_request_map=_in_request_map(src, line),
                    is_firebase_config=is_firebase,
                    in_legal_body=bool(legal and legal[0] < line < legal[1]),
                    ignored_because=ignore_reason(src, line),
                )
                rows.append((path, line, value, category, reason))

    counts = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}
    for row in rows:
        counts[row[3]] += 1

    out_path = os.path.join("..", "docs", "localization_hardcoded_audit.md")
    with io.open(out_path, "w", encoding="utf-8", newline="") as out:
        out.write("# Hard-coded visible-string audit\n\n")
        out.write("Regenerate with `python tool/audit_report.py` from "
                  "`easyrepair_app/`.\n\n")
        out.write("Every literal that `tool/extract_ui_strings.py` finds in a "
                  "user-visible position is classified into exactly one "
                  "category.\n\n")
        out.write("| Category | Meaning | Count |\n|---|---|---|\n")
        out.write("| 1 | Dynamic / user / backend content that must remain "
                  "unchanged | %d |\n" % counts[1])
        out.write("| 2 | Protected bottom-navigation English | %d |\n" % counts[2])
        out.write("| 3 | Internal technical value, or a fixed name no language "
                  "changes | %d |\n" % counts[3])
        out.write("| 4 | **Missed app-owned visible text that must be "
                  "localized** | **%d** |\n" % counts[4])
        out.write("| 5 | Approved English-only legal document content awaiting "
                  "professional translation | %d |\n\n" % counts[5])

        if counts[4]:
            out.write("> **This audit does not pass.** Category 4 must reach "
                      "zero before the localization work is complete.\n\n")
        else:
            out.write("> Audit passes: no app-owned visible string remains "
                      "hard-coded.\n\n")

        out.write("Category 5 is a product and legal decision, not missed "
                  "work. The Privacy Policy and Terms bodies stay in their "
                  "approved English wording until a professionally approved "
                  "Urdu and Roman Urdu translation exists; the app chrome "
                  "around them, including the notice that says the document "
                  "is English only, *is* localized. See "
                  "`legal_translation_exclusions.md`.\n\n")

        legal_rows = [r for r in rows if r[3] == 5]
        if legal_rows:
            out.write("## Category 5 — approved English-only legal content\n\n")
            by_file = {}
            for path, _line, _value, _cat, _reason in legal_rows:
                by_file[path] = by_file.get(path, 0) + 1
            out.write("| File | Strings |\n|---|---|\n")
            for path in sorted(by_file):
                out.write("| `%s` | %d |\n" % (path, by_file[path]))
            out.write("\n| File | Line | Literal | Reason |\n|---|---|---|---|\n")
            for path, line, value, _cat, reason in legal_rows:
                safe = value.replace("|", "\\|").replace("\n", " ")
                if len(safe) > 90:
                    safe = safe[:87] + "..."
                out.write("| `%s` | %d | `%s` | %s |\n"
                          % (path, line, safe, reason))
            out.write("\n")

        outstanding = {}
        for path, line, value, category, _reason in rows:
            if category == 4:
                outstanding.setdefault(path, []).append((line, value))

        if outstanding:
            out.write("## Category 4 by file — the remaining work\n\n")
            out.write("| File | Remaining |\n|---|---|\n")
            for path in sorted(outstanding, key=lambda k: -len(outstanding[k])):
                out.write("| `%s` | %d |\n" % (path, len(outstanding[path])))
            out.write("\n")

        out.write("## Full listing\n\n")
        out.write("| File | Line | Literal | Category | Reason |\n")
        out.write("|---|---|---|---|---|\n")
        for path, line, value, category, reason in rows:
            safe = value.replace("|", "\\|").replace("\n", " ")
            if len(safe) > 90:
                safe = safe[:87] + "..."
            out.write("| `%s` | %d | `%s` | %d | %s |\n"
                      % (path, line, safe, category, reason))

    print("categories:", counts)
    print("written:", os.path.abspath(out_path))
    return 0 if counts[4] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
